### ISSUE TITLE
sonar-measures-export doesnt return accurate value for LoC in branch

### ISSUE THREAD

**Issue by cyrilleTixierLefebreDalloz** [okorach/sonarqube-tools#191]
i use sonar-measures-export with branch options in order to get the count of line of code for every branch but the return seems to give me always the same loc count : those get on master branch.

**Comment by okorach** [comment]
Thank you @cyrilleTixierLefebreDalloz for reporting the problem.
This is fixed in [sonar-tools 1.4.7](https://pypi.org/project/sonar-tools/)

**Comment by cyrilleTixierLefebreDalloz** [comment]
Hello
after reinstall, i got an issue i didnt have before : 
2021-11-17 19:13:26,331 | sonarqube-tools | CRITICAL | HTTP fatal error 404 - 404 Client Error:  for url: http://<sonar url>/api/project_dump/export?key=myprojectKey
404 Client Error:  for url: http://<sonar url>/api/project_dump/export?key=myprojectKey
the project with 404 is a project with no line in master branch but have lines in a develop branch. I didn't have this error before the fix.

**Comment by okorach** [comment]
Hello @cyrilleTixierLefebreDalloz see my comment at https://github.com/okorach/sonarqube-tools/issues/195#issuecomment-973240631
