### ISSUE TITLE
Add LoC counts per project

### ISSUE THREAD

**Issue by sylvain-combe-sonarsource** [okorach/sonarqube-tools#231]
Getting LoC dispatches per project is apretty common need, presently considered for [roadmap addition](https://portal.productboard.com/sonarsource/3-sonarqube/c/167-show-how-projects-contribute-to-license-lines-of-code).
It would be great to get it as one of the sonarqube tools here before it's available out of the box :-)
WDYT @okorach

**Comment by okorach** [comment]
Coming in next release 1.6 @sylvain-combe-sonarsource:
Usage:

sonar-loc -u <SONAR_HOST_URL> -t <SONAR_TOKEN>

-u and -t not needed if env vars $SONAR_HOST_URL and $SONAR_TOKEN are set.

Release planned for Dec 4th or Dec 11th
The code is merged this weekend for sure

**Comment by okorach** [comment]
@sylvain-combe-sonarsource: sonar-tools v1.6 released today introduces a new tool **sonar-loc** that should do what you wished for
